version: "3.8"

services:
  spring-boot-app:
    image: seojaejun/littlepetdocker:latest
    container_name: littlepet-container
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend_my-network
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TZ=Asia/Seoul

  frontend:
    build:
      context: ./LittlePet_Front  # ✅ Vue 프로젝트 위치
      dockerfile: Dockerfile
    container_name: littlepet-frontend
    restart: always
    networks:
      - backend_my-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend_my-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # ✅ SSL 인증서 마운트

networks:
  backend_my-network:
    name: backend_my-network
    driver: bridge