version: "3.8"

services:
  # Spring Boot 서비스
  spring-boot-app:
    image: seojaejun/littlepetdocker:latest
    container_name: littlepet-container
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my-network
    env_file:
      - .env   # <-- 환경 변수 파일 로드 추가
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - TZ=Asia/Seoul

  # Nginx Reverse Proxy 서비스
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring-boot-app
    networks:
      - my-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  my-network:
    driver: bridge