name: CI/CD using GitHub Actions & Docker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test
        shell: bash

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Docker Image Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/littlepetdocker:latest
          cache-from: type=registry
          cache-to: type=inline

      - name: Update Code & Restart Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Backend

            # 최신 코드 가져오기 (강제 리셋)
            git reset --hard origin/main
            git pull origin main

            # 기존 컨테이너 중지 및 삭제
            docker-compose down

            # 기존 이미지 삭제
            docker rmi -f $(docker images seojaejun/littlepetdocker -q) || true

            # 최신 Docker 이미지 가져오기
            docker pull seojaejun/littlepetdocker:latest

            # 사용하지 않는 네트워크 삭제
            docker network prune -f

            # 최신 Docker Compose 설정 적용
            docker-compose pull
            docker-compose up -d --build